[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
ENVIRONMENT = "production"
HOST = "0.0.0.0"
PORT = "${{ PORT }}" 